name: Build Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Temporarily modify the rust toolchain version
      run: rustup override set nightly
    - name: Install dependencies
      run: sudo apt install libdbus-1-dev libudev-dev pkg-config
    - name: Build
      run: cargo build --release
    - name: Move binary
      run: mv target/release/flipper-pc-monitor-backend-usb Flipper-Zero-PC-Monitor-USB-Linux-x86_64
    - name: Upload release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Flipper-Zero-PC-Monitor-USB-linux-x86_64

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Temporarily modify the rust toolchain version
      run: rustup override set nightly
    - name: Build
      run: cargo build --release
    - name: Move binary
      run: mv target/release/flipper-pc-monitor-backend-usb.exe Flipper-Zero-PC-Monitor-USB-windows-x86_64.exe
    - name: Upload release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Flipper-Zero-PC-Monitor-USB-windows-x86_64.exe
